Caching/RedisExchangeApiWebApp/Models/ErrorViewModel.cs
namespace RedisExchangeApiWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Caching/RedisExchangeApiWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApiWebApp.Models;
using System.Diagnostics;

namespace RedisExchangeApiWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Caching/RedisExchangeApiWebApp/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using RedisExchangeApiWebApp.Services;
using StackExchange.Redis;

namespace RedisExchangeApiWebApp.Controllers
{
    public class ListTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase db;
        private string listKey = "names";

        public ListTypeController(RedisService redis)
        {
            _redis = redis;
            db = _redis.GetDb(1);
        }
        public IActionResult Index()
        {
            List<string> nameList = new List<string>();

            if (db.KeyExists(listKey))
            {
                db.ListRange(listKey).ToList().ForEach(x => {
                    nameList.Add(x.ToString());
                });
            }
            return View(nameList);
        }

        [HttpPost]
        public IActionResult Add(string name)
        {
            if (name.StartsWith('a'))
            {
                db.ListLeftPush(listKey,name);
            }
            else
            {
                db.ListRightPush(listKey, name);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteItemAsync(string name)
        {
            await db.ListRemoveAsync(listKey, name);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteFirstItem()
        {
            await db.ListLeftPopAsync(listKey);
            return RedirectToAction("Index");
        }
    }
}

Caching/RedisExchangeApiWebApp/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApiWebApp.Services;
using StackExchange.Redis;

namespace RedisExchangeApiWebApp.Controllers
{
    public class StringTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase db;

        public StringTypeController(RedisService redis)
        {
            _redis = redis;
            db = _redis.GetDb(1);
        }
        public IActionResult Index()
        {
            db.StringSet("name", "Kaan Furkan Çakıroğlu");
            db.StringSet("ziyaretçi", 1000);

            return View();
        }

        public async Task<IActionResult> ShowAsync()
        {
            var value = await db.StringGetAsync("name");
            value = db.StringGetRange("name", 0, 2);
            value = db.StringLength("name");
            
            await db.StringIncrementAsync("ziyaretçi",2);
            var count = await db.StringDecrementAsync("ziyaretçi", 23);
            if (value.HasValue)
            {
                ViewBag.value = value.ToString();
            }
            return View();
        }
    }
}

Caching/RedisExchangeApiWebApp/Views/ListType/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Caching/RedisExchangeApiWebApp/Views/ListType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<string>

<a asp-action="DeleteFirstItem">Delete First Name</a>
<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Save</button>
</form>


@foreach (var item in Model){
    <h3>@item <a asp-controller="ListType" asp-action="DeleteItem" asp-route-name="@item">sil</a></h3>
}

Caching/RedisExchangeApiWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisExchangeApiWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RedisExchangeApiWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisExchangeApiWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RedisExchangeApiWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Caching/RedisExchangeApiWebApp/Views/StringType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Caching/RedisExchangeApiWebApp/Views/StringType/Show.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>@ViewBag.value</h2>